---
base_locale: en
data:
  read:

  write:

  external:

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

search:
  paths:
    - app/
    - lib/

  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos

ignore_unused:
  - 'activerecord.attributes.*'
  - 'spree.check'
  - 'spree.order_state.payment_confirm'
  - 'spree.payment_has_been_cancelled'

<% I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper', patterns: [['\bSpree\.t[( ]\s*%{key}', 'spree.%{key}']] %>
